# Generated by Django 5.1.5 on 2025-04-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pub_date',
            new_name='created_at',
        ),
    ]
